grant select on murr_data.fin_attribute_types to karma_saver;
grant select on murr_data.fin_attributes to karma_saver;
grant select on murr_data.fin_data_sources to karma_saver;
grant select on murr_data.fin_date_value to karma_saver;
grant select on murr_data.fin_instrument_fin_attribute to karma_saver;
grant select on murr_data.fin_instruments to karma_saver;
grant select on murr_data.fin_numeric_value to karma_saver;
grant select on murr_data.fin_string_value to karma_saver;
grant select on murr_data.time_series to karma_saver;