REVOKE ALL ON SCHEMA murr_data FROM PUBLIC;
GRANT USAGE ON SCHEMA murr_data  TO karma_saver;

--ACCESS TABLES
REVOKE ALL ON ALL TABLES IN SCHEMA murr_data FROM PUBLIC;
GRANT USAGE ON SCHEMA murr_data TO karma_saver;

REVOKE ALL ON ALL TABLES IN SCHEMA murr_data FROM karma_saver ;